name: AkaniCrates
main: it.einjojo.akani.crates.CratesPlugin
version: ${version}
author: EinJoJo
description: AkaniCrates plugin
api-version: 1.19
softdepend:
  - LuckPerms
libraries: ["${caffeine}", "${hikari}"]